# Generated by Django 2.0.7 on 2018-10-29 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endzeit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Endzeit_bis', models.DateTimeField(verbose_name='%d/%m/%y %H:%M')),
            ],
        ),
        migrations.CreateModel(
            name='Startzeit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startzeit_ab', models.DateTimeField(verbose_name='%d/%m/%y %H:%M')),
            ],
        ),
        migrations.CreateModel(
            name='Wartungen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wartungsname', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='startzeit',
            name='wartungen1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wartung.Wartungen'),
        ),
        migrations.AddField(
            model_name='endzeit',
            name='wartungen2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wartung.Wartungen'),
        ),
    ]
