# Generated by Django 2.0.7 on 2018-10-29 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wartung', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wartungen',
            old_name='wartungsname',
            new_name='wartungen_text',
        ),
    ]
