# Generated by Django 2.0.7 on 2018-11-19 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wartung', '0003_auto_20181119_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wartungen',
            name='endzeit',
            field=models.DateTimeField(verbose_name='endet:'),
        ),
        migrations.AlterField(
            model_name='wartungen',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='wartungen',
            name='startzeit',
            field=models.DateTimeField(verbose_name='beginnt:'),
        ),
    ]
