# Generated by Django 2.0.7 on 2018-11-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wartung', '0004_auto_20181119_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wartungen',
            name='wartungen_text',
            field=models.CharField(max_length=200, verbose_name='Wartungstext'),
        ),
    ]
