# Generated by Django 2.0.7 on 2018-11-26 11:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wartung', '0005_auto_20181119_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='wartungen',
            name='pub_date_modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 11, 38, 30, 535296, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='wartungen',
            name='pub_date',
            field=models.DateTimeField(editable=False),
        ),
    ]
