# Generated by Django 2.0.7 on 2018-11-26 11:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wartung', '0006_auto_20181126_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wartungen',
            name='pub_date_modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 11, 40, 51, 17216, tzinfo=utc)),
        ),
    ]
