# Generated by Django 2.0.7 on 2018-11-26 11:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wartung', '0007_auto_20181126_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wartungen',
            name='pub_date_modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 11, 41, 31, 360046, tzinfo=utc)),
        ),
    ]
