# Generated by Django 2.0.7 on 2018-12-17 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wartung', '0010_auto_20181126_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='wartungen',
            name='wartungen_name',
            field=models.TextField(default=django.utils.timezone.now, max_length=50, verbose_name='Wartungsname'),
            preserve_default=False,
        ),
    ]
