# Generated by Django 2.0.7 on 2018-12-17 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wartung', '0012_auto_20181217_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='wartungen',
            name='domain',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Domain'),
            preserve_default=False,
        ),
    ]
