# Generated by Django 2.1.4 on 2018-12-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wartung', '0013_wartungen_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wartungen',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='wartungen',
            name='endzeit',
            field=models.DateTimeField(null=True, verbose_name='endet:'),
        ),
        migrations.AlterField(
            model_name='wartungen',
            name='startzeit',
            field=models.DateTimeField(null=True, verbose_name='beginnt:'),
        ),
    ]
