# Generated by Django 2.1.4 on 2018-12-18 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wartung', '0014_auto_20181218_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='wartungen',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
