# Generated by Django 2.1.4 on 2018-12-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wartung', '0015_wartungen_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wartungen',
            name='pub_date',
        ),
    ]
